### ISSUE TITLE
A sort of start of a roadmap

### ISSUE THREAD

**Issue by Neradoc** [Neradoc/circuitpython-web-packager#1]
The goal for the workflow code is to run on all workflows, possibly on circuitpython.org. This requires separating the UI and app logic from the backend (BLE workflos, Web workflow, USB workflow ?). The bundle logic is already separated in circup.js.

- [ ] Refactor workflow-directory.js using jquery and cleaner logic.
- [ ] Factor out all direct call to the web workflow into a module with a workflow agnostic API.
  - [ ] First do it for the directory module as a start.
  - [ ] Apply it to the workflow module next.
- [ ] See about splitting the workflow module into the logic (based on the above API) and interface.
- [ ] Test the static files version of the bundle (`http://.../bundle/something-7mpy-latest.zip` or such).

UI wise, there are some things to settle too. The current desired logic is to have parameters related to the context as URL parameters, while the current tab is the hash. The page needs to load a bunch of things, not to mention remember the password, so in-page loads are preferred to reloading the page.

- [ ] Ask for the password dynamically.
  - [ ] When we are doing an action that needs it and none is defined.
  - [ ] When we get an unauthorized error.
- [ ] Checkbox to memorize the password (in the NON-secure browser localStorage).
- [ ] Share the password in sessionStorage so it works in multiple windows.
- [ ] Handle every error from the workflow backend (unauthorized, etc.)
- [ ] Figure out how to open/edit files.
  - [ ] Open the editor in the same window ? This allows using the password.
  - [ ] Open files in a new window/tab, using sessionStorage for the password.
  - [ ] Embed the on-board editor (iframe ?) with enrichment.
  - [ ] Open files in the on-board editor.
- [ ] Issue a warning/confirmation dialog when opening a secrets file.

Other features:

- [ ] Dedicated UI to edit secrets.py / .env.
  - [ ] Hides the secret values in password fields.
  - [ ] Has a list of suggestions, like Adafruit IO entries, time zones, open weather...

Now about that electron app...

- [ ] Standalone app version.
  - [ ] Check that the module imports work in there, seemed complicated.
  - [ ] Separate local file "workflow" as another backend.
  - [ ] Download and cache the bundles locally like circup does.
